### ISSUE TITLE
DLS user_roles not working properly

### ISSUE THREAD

**Issue by Tawel** [floragunncom/search-guard#105]
I'm trying to create an authorization mechanism with searchguard to an elastic index.
I am doing it by having a field on each entry that specifies which roles can see the entry (may have several roles specifed). Then using the user_roles DLS filter, Im filtering out the entries that the user cannot see and returning only those he can based on the roles he has.
Doing it i noticed that the DLS filter doesn't work when the DLS term has a hyphen or even capital letter. So for example if I have a role named "crazy-role" (or crazyRole) and obviously a field on some entries with the value "crazy-role" the DLS filter won't filter the documents accordingly.
For a role named "crazy_role" or "role" it works fine.
It is inconvenient and i hope you will fix it soon.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
