### ISSUE TITLE
Windows configuration and installation example

### ISSUE THREAD

**Issue by iano123** [floragunncom/search-guard#138]
Hi guys.

I need to use windows as  much as possible at work. I would like to use linux but I can't. So my question: Does this work on windows? I see it's written in java so I assume it does. However I also see some c++.

If it does work on windows, could you add an installation section for windows? 

Many thanks!

**Comment by floragunncom** [comment]
It works well on windows (make sure you use Oracle Java 8). If you do not want to use native OpenSSL support its all pure Java and so there no problem running this on windows.

If you like to use native OpenSSL (instead of built in JCE) then look here how to get it running on Windows http://netty.io/wiki/forked-tomcat-native.html You have two options: Either you build APR yourself and install OpenSSL on Windows (thats the hard way) or you use the statically linked boringssl lib which is a google fork from OpenSSL. The netty project will hopefully provide soon also statically linked libs for OpenSSL and LibreSSL for windows.

The installation for Windows is not really different from Linux installation.

**Comment by floragunncom** [comment]
.bat files added by https://github.com/floragunncom/search-guard/commit/5833e38278a2af623f1f86a541202b995b7e4bab

**Comment by VinodHY** [comment]
Hi @iano123  .. 

Even i am in the same situation as that of yours. I need to windows as much as possible. Right now i am working on setting up searchguard plugin for ELK. Can you please help me. It will be great if you can share me your mail id, we can discuss through mails.

**Comment by raajheshkannaa** [comment]
We are facing the same issue as described here in this thread - https://groups.google.com/d/msg/search-guard/qmHf_hLfIS0/YJWU3NslAgAJ. Still with no progress.
We believe the setup in Windows is not as smooth as in Linux.
Is there a bundle for Windows like we have for Linux or OS X. Please advise
