### ISSUE TITLE
Could it be dynamic to add host to es while not to restart es?

### ISSUE THREAD

**Issue by linjianzhong** [floragunncom/search-guard#159]
I want to add host to es,but I don't want to restart es,can do it?
I add hosts to the sg_roles_mapping,but I try it ,find it doesn't work.
this is my plugins:

sg_readonly_and_monitor:
  backendroles:
    - admin
  hosts:
    - cp01-ocean-2506.epc.baidu.com
  users:
    - spock

Thank you!

**Comment by floragunncom** [comment]
you don't have to restart elasticsearch nodes when you change sg_roles_mapping. Just run sgadmin again and the new configuration will become effective.

**Comment by linjianzhong** [comment]
why search guard must be install search guard ssl, Could it change the code to run without search guard ssl?

**Comment by floragunncom** [comment]
Am 09/07/16 um 07:11 schrieb linjianzhong:
> why search guard must be install search guard ssl, Could it change the
> code to run without search guard ssl?

Thank you for using Search Guard®. The answer to your second question is
no, the logical relations reflecting in our architecture are like this:

Our core security module is Search Guard SSL which provides optional TLS
on the REST layer, while transport level SSL is enabled by default.

Transport SSL (node-to-node communication) is mandatory for Search
Guard® 2. Without TLS on the transport layer, authentication and
authorization does not make much sense from a security point of view.
This way we prevent attacks coming from the internal network, which
happen statistically proven more often than attacks from the outside.

Therefore Search Guard® 2 building upon Search Guard SSL relies on these
principles, please read here in detail:
https://github.com/floragunncom/search-guard-ssl-docs/blob/master/overview.md

To improve the setup of the plugins we provide a pre-configured bundle
for a quick start:
https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle

**Comment by linjianzhong** [comment]
I don't want to use authentication and authorization,because it can do by other things, will using ssl make slowly for the data transfer among the node?

**Comment by floragunncom** [comment]
I don't understand - if you do not want to use authentication and authorization, why are you using Search Guard? Since authentication and authorization is exactly what Search Guard does.

Yes, using SSL will affect the performance slightly, all security solutions come with a price. We recommend to use native OpenSSL over JCE to keep performance impact minimal.

**Comment by linjianzhong** [comment]
sorry, maybe my description is incorrect, I want to realize ip filter and authority access control,and it could be dynamically add or remove ip or other authority while it is not to restart es, other plugins doesn't realize the feature that dynamically add or remove, search guard realize the features, but it's using search guard ssl make data tranfer efficiency slowly, so I want to change search guard's code to run without search guard ssl, or could you have another plugins recommend to me that meet my need? thank you very much!

**Comment by floragunncom** [comment]
Ok, got you. Without going too much into the technical details, no, disabling SSL is not easily possible and also not recommended. You could of course hack into the code and remove all SSL-related pieces, but that would basically open many security holes and make your cluster very vulnerable for attacks. The security features of Search Guard rely on the fact that the communication between nodes is secure (SSL). 

If you want security for ES, then to the best of my knowledge the only alternative to Search Guard would be Shield from Elasticsearch, but it's not free.

Another question, when saying SLL makes the data transfer slow, did you do a performance test measuring the actual impact? I'm asking because Search Guard SSL is already in use on many large ES installations (100+ nodes), and we did not get any complaints regarding performance until know, given that you use OpenSSL, not JCE.

**Comment by linjianzhong** [comment]
thank you very much! 
Could you give me a way how to remove all SSL-related pieces,I try many time but it doesn't work, or could you tell me your code structure that I can change easily and quickly?

**Comment by floragunncom** [comment]
No sorry, we cannot do that, you'll have to dive into the code yourself. Also, my gut feeling is that the changes are not easy and quick.

**Comment by linjianzhong** [comment]
Thanks anyway, another question is could search guard could add ip,user or other authority by API,not use the sgadmin. I find search guard has the searchguard index, I attemped to add user to the searchguard index by the elasticsearch API but fail.

**Comment by floragunncom** [comment]
Yes, and it fails for a reason. The Search Guard internal index is specially secured and you cannot simply write to it. If this was not the case, it would be a major security flaw. Please also check the SG Google Group, especially this thread: https://groups.google.com/forum/#!topic/search-guard/cdhRLYgMi0I

Please note that we highly advise against a) removing SSL and b) making the SG index less secure. If you do this, you will be vulnerable against all kinds of attacks, and in our opinion would render Search Guard basically useless.

Regarding the API, there is an issue already to allow updating the SG index via HTTPs. If you want to do it via API, please have a look at the class SearchGuardAdmin. The sgadmin.sh shell script is just a wrapper for executing this class.

**Comment by linjianzhong** [comment]
By the way, do you know Shield also use SSL among nodes or not?

**Comment by floragunncom** [comment]
AFAIK Shield can use SSL/TLS or symmetric encryption between nodes.

**Comment by floragunncom** [comment]
Closing because it's not about bugs or issues, if you want to continue conversation please use the SG Google Group.
