### ISSUE TITLE
curator v3.5.1: (with SSL) [Elasticsearch 2.3.4(secured, not running behind any proxy), Search-Guard-2]

### ISSUE THREAD

**Issue by sagh0900** [floragunncom/search-guard#196]
# curator v3.5.1: (with SSL) [Elasticsearch 2.3.4(secured, not running behind any proxy), Search-Guard-2]

**I'm not sure whether it is search-guard related or curator related. But the curator was working fine before search-guard installation.** 

**I'm running curator from elected master-node:**

When I run command with out master-only flag, it return output though with exceptions.

> curator --loglevel DEBUG --use_ssl --host 192.168.0.1 --http_auth admin:admin --certificate "/usr/local/bin/root-ca.pem" --port 9200 show indices --all-indices

**output:**

> INFO Matching indices:
> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
> InsecureRequestWarning)
> monitoring-2016.08.09
> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
> InsecureRequestWarning)
> **searchguard**

**But when I include, master-only flag, it says connection failure, non-master node detected.**

> curator --master-only --loglevel DEBUG --use_ssl --host 192.168.0.1 --http_auth admin:admin --certificate "/usr/local/bin/root-ca.pem" --port 9200 show indices --all-indices

**output:**

> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
> InsecureRequestWarning)
> 2016-08-12 08:23:15,939 INFO Master-only flag detected. Connected to non-master node. Aborting.

**Also, how to verify certificate?, when I remove --master-only flag, again I get output with exceptions irrespective of --ssl-no-validate flag**

> curator --loglevel DEBUG --use_ssl --ssl-no-validate --host 172.16.189.41 --http_auth elk-master:VGTCloudInfra --certificate "/usr/local/bin/root-ca.pem" --port 9200 show indices --all-indices

**output:**

> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
> InsecureRequestWarning)
> monitoring-2016.08.09
> /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
> InsecureRequestWarning)
> **searchguard**

**I'm trying to avoid the exceptions in output and also want to make it run while using --master-only flag.**

**Comment by floragunncom** [comment]
For the warning i guess you have to ask this in the curator forum (is it just a warning but works otherwise?)
Regarding the master only topic i guess you have to run curator on all nodes and curator itself detects which one is the elected master cause this can change frequently. 

Pls. see also:
https://groups.google.com/forum/#!topic/search-guard/BBtKR5moF6Q
https://discuss.elastic.co/t/curator-over-ssl/52303

**Comment by floragunncom** [comment]
Currently curator is not running well with Search Guard because the Python SSL situation is kind of clumsy. To make curator work you can try:

* Disable SSL for HTTP (Caution: This makes communication insecure and password are transferred in plain text over the network)
* Better use `ssl_no_validate: False` or `--ssl-no-validate`
* Install curator via the APT or YUM Repository (this installs all packaged as a single binary package), see https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html

More on the Python SSL situation

* https://www.elastic.co/guide/en/elasticsearch/client/curator/current/security-errors.html
* https://www.elastic.co/guide/en/elasticsearch/client/curator/current/python-security.html

**Comment by floragunncom** [comment]
See also https://github.com/elastic/curator/issues/780
