### ISSUE TITLE
using searchguard for some day, I find the heap capacity is growing up, it course memery leak!

### ISSUE THREAD

**Issue by linjianzhong** [floragunncom/search-guard#202]
elasticsearch 2.3.2   searchguard 2.3.2.0-beta2
using searchguard for some day, I find the heap capacity is growing up, it course memery leak, I use jmap to dump heap , using eclipse mat to analyze , I find the object taskManager couse the heap leak!

**Comment by floragunncom** [comment]
Please install latest version of Search Guard (https://github.com/floragunncom/search-guard/wiki) and Search Guard SSL (https://github.com/floragunncom/search-guard-ssl/wiki). We had a few issues with memory leaks but they are all fixed in recent versions. beta2 is really pretty old and we do not support it because its a pre-release version. If you see memory leaks with recent SG versions please reopen this ticket or create a new one.
