### ISSUE TITLE
Download website not available via HTTPS

### ISSUE THREAD

**Issue by itay-grudev** [floragunncom/search-guard#205]
It really is a problem to download a security plugin via non-secure connection. Please get an HTTPS certificate for your downloads.floragunn.com server.

**Comment by floragunncom** [comment]
The "official" way to download and install the plugin is via maven. This is HTTPS as well as pgp  signed. The site you refer to is the download page for the Search Guard Bundle which is not supposed to be deployed to production.

So pls. look here     http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-2%22 and http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-ssl%22 . The pgp key you can validate against is here https://github.com/floragunncom/search-guard/blob/master/KEYS and we strongly recommend you do this instead of relying only on a SSL secured connection.

Despite of this we will provide SSL secured downloads and pgp signature for the bundle soon.

**Comment by floragunncom** [comment]
Changed download location to https://floragunn.com/downloads/ and added SHA-256 hash.
