### ISSUE TITLE
Allow upgrade SearchGuard plugin

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#278]
Currently, SearchGuard plugin can be either installed or removed. Please provide the option to upgrade the plugin. When plugin is removed and than installed, all the configuration files are deleted and therefore all the changes made in the configuration files are lost.

**Comment by floragunncom** [comment]
Not sure if i understand but the provided configs (in sgconfig/) are meant as examples or a starting point and you are free to copy those to any location on the filesystem you like. Then refer to them with the "-cd" option of sgadmin. Apart from this there is also an option "-r" in sgadmin to retrieve the currently stored configuration in case you lost your config files. In addition you are not enforced to execute sgadmin from within the plugins/ directory on a node because there is a standalone sgadmin version which could be used to execute sgadmin from a desktop machine: https://github.com/floragunncom/search-guard/wiki

**Comment by floragunncom** [comment]
This can be achieved with a simple shell script or similar. 

The reason why we do not provide such a script is thats its very likely you also need to update the commercial jar's alongside with the update of Search Guard.
