### ISSUE TITLE
sgadmin.sh failed

### ISSUE THREAD

**Issue by robertchen** [floragunncom/search-guard#282]
* Search Guard and Elasticsearch version
Both are 5.1.1
* JVM version and operating system version
JDK 1.8, AWS linux 
* Number of nodes in your cluster
3
* Description of the bug
[root@ip-10-8-8-246 search-guard-5]# tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/kirk-keystore.jks -kspass changeit -cd sgconfig/ -icl -nhnv -h 10.8.8.246 -cn ELK-TUHAO
Search Guard Admin v5
Will connect to 10.8.8.246:9300 ... done
Contacting elasticsearch cluster 'ELK-TUHAO' and wait for YELLOW clusterstate ...
Clustername: ELK-TUHAO
Clusterstate: GREEN
Number of nodes: 3
Number of data nodes: 3
searchguard index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/search-guard-5/sgconfig
Will update 'config' with sgconfig/sg_config.yml
   FAIL: Configuration for 'config' failed because of ElasticsearchSecurityException[Search Guard not initialized (SG11) for indices:admin/mapping/put. See https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md]
Will update 'roles' with sgconfig/sg_roles.yml
   FAIL: Configuration for 'roles' failed because of ElasticsearchSecurityException[Search Guard not initialized (SG11) for indices:admin/mapping/put. See https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md]
Will update 'rolesmapping' with sgconfig/sg_roles_mapping.yml
   FAIL: Configuration for 'rolesmapping' failed because of ElasticsearchSecurityException[Search Guard not initialized (SG11) for indices:admin/mapping/put. See https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md]
Will update 'internalusers' with sgconfig/sg_internal_users.yml
   FAIL: Configuration for 'internalusers' failed because of ElasticsearchSecurityException[Search Guard not initialized (SG11) for indices:admin/mapping/put. See https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md]
Will update 'actiongroups' with sgconfig/sg_action_groups.yml
   FAIL: Configuration for 'actiongroups' failed because of ElasticsearchSecurityException[Search Guard not initialized (SG11) for indices:admin/mapping/put. See https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md]
Timeout (java.util.concurrent.TimeoutException: Timeout after 30SECONDS while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups](index=searchguard))
Timeout (java.util.concurrent.TimeoutException: Timeout after 30SECONDS while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups](index=searchguard))
Timeout (java.util.concurrent.TimeoutException: Timeout after 30SECONDS while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups](index=searchguard))
Done with failures

/etc/elasticsearch/elasticsearch.yml  is:
```
#enable safe guard
searchguard.ssl.transport.keystore_filepath: elk-a-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false


searchguard.authcz.admin_dn:
  - CN=kirk, OU=client, O=client, L=Test, C=DE
```

The keys/certificates are generate with example.sh

**Comment by floragunncom** [comment]
Thats pretty strange because of:
- sgadmin reports that a searchguard index already exists (question: where does it come from?)
- if such an index exists all nodes read their initial config from it, so you should not see a "Search Guard not initialized (SG11)"

Are you sure that you have configured Search Guard in elasticsearch.yml on all three nodes?
Can you please also provide the logs of every node (on DEBUG level)?
Please also make sure you use Search Guard 5.1.1-10 and then run sgadmin with the "--diagnose" option. This will create a diagnose file, pls. post this too

**Comment by robertchen** [comment]
1. sgadmin reports searchguard index already exists because I tried to run the same command a few times;

2. Yes, I configured 5.1.1-10 with the below command on all 3 nodes:
./elasticsearch-plugin install -b com.floragunn:search-guard-5:5.1.1-10

[sgadmin_diag_trace_2017-Jan-20_21-29-39.txt](https://github.com/floragunncom/search-guard/files/720554/sgadmin_diag_trace_2017-Jan-20_21-29-39.txt)

3. the elasticsearch log is just:
[2017-01-20T21:34:32,688][WARN ][c.f.s.a.c.TransportConfigUpdateAction] [usg-elk-a] Timeout, we just try again in a few seconds ...
[2017-01-20T21:34:32,689][ERROR][c.f.s.c.ConfigurationLoader] No data for config while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups]  (index=searchguard)
[2017-01-20T21:34:32,689][ERROR][c.f.s.c.ConfigurationLoader] No data for roles while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups]  (index=searchguard)
[2017-01-20T21:34:32,689][ERROR][c.f.s.c.ConfigurationLoader] No data for rolesmapping while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups]  (index=searchguard)
[2017-01-20T21:34:32,689][ERROR][c.f.s.c.ConfigurationLoader] No data for internalusers while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups]  (index=searchguard)
[2017-01-20T21:34:32,689][ERROR][c.f.s.c.ConfigurationLoader] No data for actiongroups while retrieving configuration for [config, roles, rolesmapping, internalusers, actiongroups]  (index=searchguard)
[2017-01-20T21:34:34,291][ERROR][c.f.s.a.BackendRegistry  ] Not yet initialized (you may need to run sgadmin)
[2017-01-20T21:34:36,796][ERROR][c.f.s.a.BackendRegistry  ] Not yet initialized (you may need to run sgadmin)
...

**Comment by floragunncom** [comment]
Pls execute:
`tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/kirk-keystore.jks -kspass changeit -cd sgconfig/ -nhnv -h 10.8.8.246 -cn ELK-TUHAO --diagnose  --delete-config-index`

And then:
`tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/kirk-keystore.jks -kspass changeit -cd sgconfig/ -nhnv -h 10.8.8.246 -cn ELK-TUHAO --diagnose`

Pls. post the complete output of sgadmin and the logs from ALL your nodes on DEBUG level (just INFO or WARN is not enough!)

**Comment by floragunncom** [comment]
And please provide the full elasticsearch.yml of all three nodes

**Comment by robertchen** [comment]
can you please help how to set elasticsearch log level to DEBUG level? my cluster is 5.1.1, I googled and could not find. Thanks.

**Comment by robertchen** [comment]
the trace log after this command (
tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/kirk-keystore.jks -kspass changeit -cd sgconfig/ -nhnv -h 10.8.8.246 -cn ELK-TUHAO --diagnose --delete-config-index) 

[sgadmin_diag_trace_2017-Jan-23_14-53-50.txt](https://github.com/floragunncom/search-guard/files/727605/sgadmin_diag_trace_2017-Jan-23_14-53-50.txt)

The trace log after (tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/kirk-keystore.jks -kspass changeit -cd sgconfig/ -nhnv -h 10.8.8.246 -cn ELK-TUHAO --diagnose)

[sgadmin_diag_trace_2017-Jan-24_17-59-17.txt](https://github.com/floragunncom/search-guard/files/727607/sgadmin_diag_trace_2017-Jan-24_17-59-17.txt)


## All 3 nodes logs:

[usg-elk-a.txt](https://github.com/floragunncom/search-guard/files/727608/usg-elk-a.txt)
[usg-elk-b.txt](https://github.com/floragunncom/search-guard/files/727609/usg-elk-b.txt)
[usg-elk-c.txt](https://github.com/floragunncom/search-guard/files/727612/usg-elk-c.txt)

###  Node a elasticsearch.yml:
cluster.name: ELK-TUHAO
path.data: /data
node.name: usg-elk-a
network.host: 10.8.8.246
action.destructive_requires_name: true
bootstrap.memory_lock: true
discovery.zen.minimum_master_nodes: 2
logger._root: DEBUG

# set the list of hosts for unicast discovery, need set this in ansible
discovery.zen.ping.unicast.hosts: ['10.8.8.246', '10.8.8.209', '10.8.8.248']

#enable safe guard
searchguard.ssl.transport.keystore_filepath: usg-elk-a-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false

searchguard.authcz.admin_dn:
  - CN=kirk, OU=client, O=client, L=Test, C=DE


### node b elasticsearch.yml:
cluster.name: ELK-TUHAO
path.data: /data
node.name: usg-elk-b
network.host: 10.8.8.209
action.destructive_requires_name: true
bootstrap.memory_lock: true
discovery.zen.minimum_master_nodes: 2
logger._root: DEBUG

# set the list of hosts for unicast discovery, need set this in ansible
discovery.zen.ping.unicast.hosts: ['10.8.8.246', '10.8.8.209', '10.8.8.248']

#enable safe guard
searchguard.ssl.transport.keystore_filepath: usg-elk-b-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false

### node c elasticsearch.yml:

cluster.name: ELK-TUHAO
path.data: /data
node.name: usg-elk-c
network.host: 10.8.8.248
action.destructive_requires_name: true
bootstrap.memory_lock: true
discovery.zen.minimum_master_nodes: 2
logger._root: DEBUG

# set the list of hosts for unicast discovery, need set this in ansible
discovery.zen.ping.unicast.hosts: ['10.8.8.246', '10.8.8.209', '10.8.8.248']

#enable safe guard
searchguard.ssl.transport.keystore_filepath: usg-elk-c-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false

**Comment by floragunncom** [comment]
you need to set configure
<pre>
searchguard.authcz.admin_dn:
  - CN=kirk, OU=client, O=client, L=Test, C=DE
</pre>
on all nodes ! Seems its missing for node b+c

**Comment by robertchen** [comment]
Thanks a lot, seems works:

 tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/kirk-keystore.jks -kspassnv -h 10.8.8.246 -cn ELK-TUHAO --diagnose
Search Guard Admin v5
Will connect to 10.8.8.246:9300 ... done
Diagnostic trace written to: /usr/share/elasticsearch/plugins/search-guard-5/sgadmin_diag_trace_2017-Jan-24_19-37-10.txt
Contacting elasticsearch cluster 'ELK-TUHAO' and wait for YELLOW clusterstate ...
Clustername: ELK-TUHAO
Clusterstate: GREEN
Number of nodes: 3
Number of data nodes: 3
searchguard index does not exists, attempt to create it ... done (auto expand replicas is on)
Populate config from /usr/share/elasticsearch/plugins/search-guard-5/sgconfig
Will update 'config' with sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'roles' with sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'actiongroups' with sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Done with success

**Comment by Passpes** [comment]
A bit similar issue here:
tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/node-0-keystore.jks -kspass changeit -cd sgconfig/ -icl -nhnv -h 192.168.40.174 -cn admin --diagnose --delete-config-index
Search Guard Admin v5
Will connect to 192.168.40.174:9300 ... done
Diagnostic trace written to: /usr/share/elasticsearch/plugins/search-guard-5/sgadmin_diag_trace_2017-Jan-27_12-15-38.txt
Contacting elasticsearch cluster 'admin' and wait for YELLOW clusterstate ...
Clustername: elasticsearch
Clusterstate: GREEN
Number of nodes: 2
Number of data nodes: 2
No index 'searchguard' exists, so no need to delete it

and:

 tools/sgadmin.sh -ts /etc/elasticsearch/truststore.jks -tspass changeit -ks sgconfig/node-0-keystore.jks -kspass changeit -cd sgconfig/ -nhnv -h 192.168.40.174 -cn admin --diagnose
Search Guard Admin v5
Will connect to 192.168.40.174:9300 ... done
Diagnostic trace written to: /usr/share/elasticsearch/plugins/search-guard-5/sgadmin_diag_trace_2017-Jan-27_12-19-06.txt
Contacting elasticsearch cluster 'admin' and wait for YELLOW clusterstate ...
Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{uY348CWHQsu7-EFZpVZ9CA}{192.168.40.174}{192.168.40.174:9300}]. This is not an error, will keep on trying ...
   * Try running sgadmin.sh with -icl and -nhnv (If thats works you need to check your clustername as well as hostnames in your SSL certificates)
   * If this is not working, try running sgadmin.sh with --diagnose and see diagnose trace log file)

what could be the prob ?

**Comment by floragunncom** [comment]
As this is very likely not a bug lets discuss that please here: https://groups.google.com/forum/#!forum/search-guard

**Comment by kozmaz87** [comment]
This is still a problem

Search Guard Admin v6
Will connect to localhost:9300 ... done
Elasticsearch Version: 6.2.4
Search Guard Version: 6.2.4-22.1
Connected as CN=es-client,O=Qwil,L=London,C=UK
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: es-service-ireland-dev
Clusterstate: GREEN
Number of nodes: 3
Number of data nodes: 3
searchguard index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/search-guard-6/sgconfig
Will update 'sg/config' with ./sgconfig/sg_config.yml 
   FAIL: Configuration for 'config' failed because of ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
Will update 'sg/roles' with ./sgconfig/sg_roles.yml 
   FAIL: Configuration for 'roles' failed because of ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
Will update 'sg/rolesmapping' with ./sgconfig/sg_roles_mapping.yml 
   FAIL: Configuration for 'rolesmapping' failed because of ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
Will update 'sg/internalusers' with ./sgconfig/sg_internal_users.yml 
   FAIL: Configuration for 'internalusers' failed because of ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
Will update 'sg/actiongroups' with ./sgconfig/sg_action_groups.yml 
   FAIL: Configuration for 'actiongroups' failed because of ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]
Done with failures

**Comment by botzill** [comment]
I also experience this issue, any updates on this?

**Comment by floragunncom** [comment]
@botzill Please provide

- ES/SG Version
- Your full sgadmin command + Output
- complete elasticsearch.yml respectively for every node

**Comment by botzill** [comment]
Hi @floragunncom. 

This issue is related to: https://github.com/kubedb/project/issues/468, here you can see the logs.

**Comment by floragunncom** [comment]
Not sure if this is really a Search Guard problem:

First thing i see is ```not enough master nodes discovered during pinging``` and then something like 

```
Populate config from /elasticsearch/plugins/search-guard-6/sgconfig/
Will update 'sg/config' with /elasticsearch/plugins/search-guard-6/sgconfig/sg_config.yml 
   FAIL: Configuration for 'config' failed because of java.io.FileNotFoundException: /elasticsearch/plugins/search-guard-6/sgconfig/sg_config.yml (No such file or directory)
Will update 'sg/roles' with /elasticsearch/plugins/search-guard-6/sgconfig/sg_roles.yml 
   FAIL: Configuration for 'roles' failed because of java.io.FileNotFoundException: /elasticsearch/plugins/search-guard-6/sgconfig/sg_roles.yml (No such file or directory)
Will update 'sg/rolesmapping' with /elasticsearch/plugins/search-guard-6/sgconfig/sg_roles_mapping.yml 
   FAIL: Configuration for 'rolesmapping' failed because of java.io.FileNotFoundException: /elasticsearch/plugins/search-guard-6/sgconfig/sg_roles_mapping.yml (No such file or directory)
Will update 'sg/internalusers' with /elasticsearch/plugins/search-guard-6/sgconfig/sg_internal_users.yml 
   FAIL: Configuration for 'internalusers' failed because of java.io.FileNotFoundException: /elasticsearch/plugins/search-guard-6/sgconfig/sg_internal_users.yml (No such file or directory)
Will update 'sg/actiongroups' with /elasticsearch/plugins/search-guard-6/sgconfig/sg_action_groups.yml 
   FAIL: Configuration for 'actiongroups' failed because of java.io.FileNotFoundException: /elasticsearch/plugins/search-guard-6/sgconfig/sg_action_groups.yml (No such file or directory)

```

which means simply that there is no file /elasticsearch/plugins/search-guard-6/sgconfig/sg_action_groups.yml and therefore Search Guard can not be initialized.

You can also have a look here when dealing with helm: https://github.com/floragunncom/search-guard-helm

**Comment by botzill** [comment]
Thx. Yes I managed to fix that, files were not present. First time using
:).

Thx a lot.
