### ISSUE TITLE
Config examples

### ISSUE THREAD

**Issue by pemontto** [floragunncom/search-guard#3]
It would be great if you supplied more in depth example configurations. For instance showing how to replicate the Shield config guides for particular clients would be very helpful. Guides for [Kibana3](https://www.elastic.co/guide/en/shield/current/_shield_with_kibana_3.html), [Kibana4](https://www.elastic.co/guide/en/shield/current/_shield_with_kibana_4.html), [Marvel](https://www.elastic.co/guide/en/shield/current/marvel.html), [Logstash](https://www.elastic.co/guide/en/shield/current/logstash.html)

**Comment by fbaligand** [comment]
+1
Personnally, I would like more config examples for DLS include/exclude fields

**Comment by floragunncom** [comment]
stay tuned, more docs and examples will appear soon

**Comment by julienbeclin** [comment]
On my side, I would like to give access to my ".kibana" index to all users and then filter on other index to control access to data and filter on index-pattern (which is a field of the .kibana index) to control access to visualtisations and dashboard !
I have tried this configuration : 

```json
# Configure the actionrequestfilter to allow or forbid action 
searchguard.actionrequestfilter.names: ["readonly"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*", "indices:admin*", "indices:data/write*"]

# Configure document level security (dls) filter
searchguard.dlsfilter.names: ["dashboard","index-pattern"]
searchguard.dlsfilter.dashboard: ["term", "title","Dashboard logs", "false"] # if field==value (or not) match
searchguard.dlsfilter.index_pattern: ["term", "index-pattern","logstash-*", "false"] # if field==value (or not) match
```

and this acl rule : 

```json
    {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": [],
      "filters_execute": ["*"]
    },

    {
    "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
    "roles": ["admin"],
    "filters_bypass": ["*"],
    "filters_execute": []
    },

    {
      "__Comment__": "Any authenticated user can do anything on the '.kibana' index - no filter will be executed",
      "indices": [".kibana"],
      "filters_bypass": ["*"],
      "filters_execute": []
    },

    {
       "__Comment__": "user1 has document level filter set for index_pattern",
       "users": ["user1"],
       "indices": [".kibana"],
       "filters_bypass": [],
       "filters_execute": ["dls.index_pattern"]
}
```

Unfortunately, I had the error : 

```
[2015-06-24 15:41:39,034][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:admin/exists (class org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest) due to type[s]() method not found
[2015-06-24 15:41:39,139][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] actionrequestfilter.readonly Action 'indices:admin/exists' is forbidden due to DEFAULT
[2015-06-24 15:41:39,158][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to java.lang.RuntimeException: Action 'indices:admin/exists' is forbidden due to DEFAULT for action indices:admin/exists
java.lang.RuntimeException: Action 'indices:admin/exists' is forbidden due to DEFAULT
```

**Comment by julienbeclin** [comment]
+1 agree with @fbaligand

**Comment by pwnmagic** [comment]
+1

**Comment by julienbeclin** [comment]
Hello,

Where are we on the config examples ?

Thanks !

**Comment by SergeyBear** [comment]
Hi all!
Had some experiments with Search-Guard and Kibana with basic auth.
All works as expected.
I decided to give not only my configs because there is some important notices.

# REQUIRED
* CentOS 7.1
* Elasticsearch 1.5.2
* Search-Guard 0.5
* Kibana 4.1.1
* Logstash 1.5.4
* Elasticsearch and Logstash installed from official repos
* Kibana installed to '/opt/kibana' and runned as user 'kibana'
* All ELK tested to work properly with installed but not enabled search-guard

Add to '/etc/elasticsearch/elasticsearch.yml'

```
searchguard.enabled: true
searchguard.key_path: /etc/elasticsearch/
#searchguard.allow_all_from_loopback: true
searchguard.http.xforwardedfor.header: DUMMY

searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend
searchguard.authentication.authentication_backend.cache.enable: false
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator
searchguard.authentication.authorizer.cache.enable: false
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

searchguard.authentication.settingsdb.user.root: passwd111
searchguard.authentication.settingsdb.user.kibana: passwd222
searchguard.authentication.settingsdb.user.logstash: passwd333
searchguard.authentication.settingsdb.user.admin: passwd444
searchguard.authentication.settingsdb.user.user: passwd555

searchguard.authentication.authorization.settingsdb.roles.root: ["root"]
searchguard.authentication.authorization.settingsdb.roles.kibana: ["kibana"]
searchguard.authentication.authorization.settingsdb.roles.logstash: ["logstash"]
searchguard.authentication.authorization.settingsdb.roles.admin: ["admin"]
searchguard.authentication.authorization.settingsdb.roles.user: ["user"]

searchguard.actionrequestfilter.names: ["kibana-server", "kibana-user", "kibana-admin", "logstash-server", "logstash-user"]
searchguard.actionrequestfilter.kibana-server.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/create*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*"
]
searchguard.actionrequestfilter.kibana-user.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*"
]
searchguard.actionrequestfilter.kibana-admin.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*",
  "indices:admin/create*"
]
searchguard.actionrequestfilter.logstash-server.allowed_actions: [
  "indices:admin/template/get*",
  "indices:admin/template/put*",
  "indices:admin/create*",
  "indices:data/write/bulk*",
  "indices:data/write/index*",
  "indices:data/write/delete*",
  "indices:data/write/update*",
  "indices:data/read/search*",
  "indices:data/read/scroll*"
]
searchguard.actionrequestfilter.logstash-user.allowed_actions: [
  "indices:admin/mappings/fields/get*",
  "indices:admin/validate/query*",
  "indices:data/read/search*",
  "indices:data/read/msearch*",
  "indices:admin/get*"
]
```

Then add to '/opt/kibana/config/kibana.yml'

```
kibana_elasticsearch_username: kibana
kibana_elasticsearch_password: passwd222
```

Logstash output '/etc/logstash/conf.d/30-lumberjack-output.conf' looks like this

```
output {
  elasticsearch {
    protocol => http
    host => localhost
    user => logstash
    password => passwd333
    #index => "logstash-%{type}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
```

**NOTICE**: To create separate index per each log type uncomment 'index' parameter. In this case specified in logstash-forwarder field 'type' will automatically be added to indice name. You also can use any fields or multiple fields you like added by logstash-forwarder. It can be very usefull  for separating access to different user roles.

Then change owners and mod of config files with passwords to be sure that only root and services can read them:

```
chown root.elasticsearch /etc/elasticsearch/elasticsearch.yml
chmod 640 /etc/elasticsearch/elasticsearch.yml

chown root.logstash /etc/logstash/conf.d/30-lumberjack-output.conf
chmod 640 /etc/logstash/conf.d/30-lumberjack-output.conf

chown root.kibana /opt/kibana/config/kibana.yml
chmod 640 /opt/kibana/config/kibana.yml
```

Before adding ACL make sure you deny all access to Kibana for users.
Uncomment in 'elasticsearch.yml' parameter 'searchguard.allow_all_from_loopback: true'.
And execute on elasticsearch host following:

```
service elasticsearch restart

curl -XPUT "http://localhost:9200/searchguard/ac/ac" -d '{
    "acl": [
    {
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
    },
    {
        "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
        "roles": ["root"],
        "filters_bypass": ["*"],
        "filters_execute": []
    },
    {
        "__Comment__": "For role *kibana* executed filter *kibana-server*.",
        "users": ["kibana"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-server"]
    },
    {
        "__Comment__": "For role *logstash* executed filter *logstash-server*.",
        "users": ["logstash"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-server"]
    },
    {
        "__Comment__": "For role *admin* executed filter *kibana-admin*.",
        "roles": ["admin"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-admin"]
    },
    {
        "__Comment__": "For role *user* executed filter *kibana-user*.",
        "roles": ["user"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-user"]
    },
    {
        "__Comment__": "For role *admin* executed filter *logstash-user*.",
        "roles": ["admin"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user"]
    },
    {
        "__Comment__": "For role *user* executed filter *logstash-user*.",
        "roles": ["user"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user"]
    }
    ]
}'

```

Then comment back 'searchguard.allow_all_from_loopback: true' and restart all together:

```
service elasticsearch restart && service kibana restart && service logstash restart
```

Now you can open Kibana to users and test authentication.

# ACCESS
All users with role 'user' can only read kibana and logstash indices.
All users with role 'admin' can edit kibana and read logstash indices.
All users with role 'root' can play god with elasticsearch :-)
All grants were taken from official Shield documentation.
For example, if you need group 'dev' that can only read indices 'logstash-nginx-*' then add to search-guard config:

```
searchguard.authentication.settingsdb.user.dev1: passwd555
searchguard.authentication.settingsdb.user.dev2: passwd666
searchguard.authentication.authorization.settingsdb.roles.dev: ["dev1", "dev2"]
```

And again apply ACL with added rule:

``` 
   {
        "__Comment__": "For role *dev* executed filter *logstash-user*.",
        "roles": ["dev"],
        "indices": ["logstash-nginx-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user"]
    }
```

# PROBLEMS
* There is a bug that allow authenticated users to see other users and their passwords in elasticsearch by executing query:

```
curl -XGET -u user -v -XGET 'http://localhost:9200/_nodes?pretty'
```

But I dont think that it's a problem while you dont give access to elasticsearch directly (not through Kibana). Fix me if I wrong :-)
* In current state I found that 'dlsfilters' and 'flsfilters' of search-guard breaks Kibana, so for now you need to use per indice-access (like Shield does)
* To apply ACL elasticsearch must be started with 'searchguard.allow_all_from_loopback: true' and set to 'false' and restarted after ACL applied.

**Comment by SergeyBear** [comment]
Hope I halped someone.

BTW, great thanks to Search-Guard developers!!! Without your efforts many admins would continue to create wheel trying to secure ELK stack.

**Comment by SergeyBear** [comment]
I also manage to deploy authentication and authorization through FreeIPA, but I'll post manual later.

**Comment by julienbeclin** [comment]
Great work and thanks for sharing !
I will try it out this week to check if it is working properly with my conf !
Thanks again

**Comment by SergeyBear** [comment]
U R welcome!

**Comment by SergeyBear** [comment]
Here is my example of connection to FreeIPA.
For completness I left identical to previous example.

# Required
* CentOS 7.1
* FreeIPA 4.1 in https://ipa.domain.com with REALM domain.com
* Elasticsearch 1.5.2
* Search-Guard 0.5
* Kibana 4.1.1
* Logstash 1.5.4
* Elasticsearch and Logstash installed from official repos
* Kibana installed to **/opt/kibana** and runned as user **kibana**
* All ELK tested to work properly with installed but not enabled search-guard

# Getting started
## Prepearing FreeIPA
In most cases anonymous binds disabled in production LDAP. So we will think that it is the case.

**NOTICE**: System user cannot write to directory server and cannot login to IPA UI. But he can read everithing from directory server. So keep it safe!

**NOTICE**: To create system user you need to have directory server account. 

On FreeIPA server host:

```
ldapmodify -x -D 'cn=Directory Manager' -W
dn: uid=elastic,cn=sysaccounts,cn=etc,dc=example,dc=com
changetype: add
objectclass: account
objectclass: simplesecurityobject
uid: mx
userPassword: passwd111
passwordExpirationTime: 20380119031407Z
nsIdleTimeout: 0
```

With IPA UI or IPA CLI:
1. Create user: **logstash**, **kibana**, **kibana.admin** and **kibana.user**
2. Create group **services** and add users **kibana** and **logstash** to it
3. Create group **kibana-admins** and add user **kibana.admin** to it
4. Create group **kibana-users** and add user **kibana.user** to it
5. Create group **elastic-users** and add to it groups **kibana-admins** and **kibana-users** and users **kibana** and **logstash**
6. Create password policy for group **services** with maximum password expiration time (max is 20000)
5. Login with each user to https://ipa.domain.com to ensure that everything is ok.


## Preparing Java
By default FreeIPA create it's own self-signed CA certificate during installation. In this case, you need to add IPA CA cert to java thrusted store on elasticsearch host or you will get an error while trying to connect IPA.

**NOTICE**: If your FreeIPA installed with CA cert signed by thrusted authority (lucky you! :-) ), then you can skip this block and proceed to ELK configurations.

On elasticsearch host:

```
cd /etc/pki/ca-trust/extracted/java
cp cacerts cacerts.bak

wget --no-check-certificate https://ipa.domain.com/ipa/config/ca.crt
keytool -keystore cacerts -importcert -alias freeipa -file ca.crt
```

Default java keystore password is **changeit**

```
keytool -list -keystore cacerts
```

Check command output that certificate added


## Preparing ELK
Add to **/etc/elasticsearch/elasticsearch.yml**

```
searchguard.enabled: true
searchguard.key_path: /etc/elasticsearch/
#searchguard.allow_all_from_loopback: true

searchguard.http.xforwardedfor.header: DUMMY

searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.ldap.LDAPAuthenticationBackend
searchguard.authentication.authentication_backend.cache.enable: false
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.ldap.LDAPAuthorizator
searchguard.authentication.authorizer.cache.enable: false
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

searchguard.authentication.ldap.host: ["ipa.domain.com:389"]
searchguard.authentication.ldap.ldaps.ssl.enabled: false
searchguard.authentication.ldap.ldaps.starttls.enabled: true

## Comment out next 3 lines in case of using thrusted certificate in FreeIPA
searchguard.authentication.ldap.ldaps.truststore_type: JKS
searchguard.authentication.ldap.ldaps.truststore_filepath: "/etc/pki/ca-trust/extracted/java/cacerts"
searchguard.authentication.ldap.ldaps.truststore_password: "changeit"

searchguard.authentication.ldap.bind_dn: "uid=elastic,cn=sysaccounts,cn=etc,dc=domain,dc=com"
searchguard.authentication.ldap.password: passwd111
searchguard.authentication.ldap.userbase: "cn=users,cn=accounts,dc=domain,dc=com"
searchguard.authentication.ldap.usersearch: (&(objectClass=posixAccount)(memberOf:=cn=elastic-users,cn=groups,cn=accounts,dc=domain,dc=com)(uid={0})(!(nsaccountlock=TRUE)))
searchguard.authentication.ldap.username_attribute: uid

searchguard.authentication.authorization.ldap.rolebase: "cn=groups,cn=accounts,dc=domain,dc=com"
searchguard.authentication.authorization.ldap.rolesearch: (&(objectClass=posixGroup)(memberOf:=cn=elastic-users,cn=groups,cn=accounts,dc=domain,dc=com)(member={0}))
searchguard.authentication.authorization.ldap.rolename: cn
searchguard.authentication.authorization.ldap.resolve_nested_roles: false

searchguard.actionrequestfilter.names: ["kibana-server", "kibana-user", "kibana-admin", "logstash-server", "logstash-user"]
searchguard.actionrequestfilter.kibana-server.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/create*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*"
]
searchguard.actionrequestfilter.kibana-user.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*"
]
searchguard.actionrequestfilter.kibana-admin.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*",
  "indices:admin/create*"
]
searchguard.actionrequestfilter.logstash-server.allowed_actions: [
  "indices:admin/template/get*",
  "indices:admin/template/put*",
  "indices:admin/create*",
  "indices:data/write/bulk*",
  "indices:data/write/index*",
  "indices:data/write/delete*",
  "indices:data/write/update*",
  "indices:data/read/search*",
  "indices:data/read/scroll*"
]
searchguard.actionrequestfilter.logstash-user.allowed_actions: [
  "indices:admin/mappings/fields/get*",
  "indices:admin/validate/query*",
  "indices:data/read/search*",
  "indices:data/read/msearch*",
  "indices:admin/get*"
]
```

**NOTICE**: If you want to use nested groups, then set **searchguard.authentication.authorization.ldap.resolve_nested_roles** to **true**.

Add to **/opt/kibana/config/kibana.yml** login and password for IPA user

```
kibana_elasticsearch_username: kibana
kibana_elasticsearch_password: passwd222
```

Add to **/etc/logstash/conf.d/30-lumberjack-output.conf** login and password for IPA user

```
output {
  elasticsearch {
    protocol => http
    host => localhost
    user => logstash
    password => passwd333
    #index => "logstash-%{type}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
```

**NOTICE**: To create separate index per each log type uncomment **index** parameter. In this case specified in logstash-forwarder field **type** will automatically be added to indice name. You also can use any fields or multiple fields you like added by logstash-forwarder. It can be very usefull  for separating access to different user roles.

Then change owners and mod of config files with passwords to be sure that only root and services can read them:

```
chown -R root.elasticsearch /etc/elasticsearch
chmod 640 /etc/elasticsearch/elasticsearch.yml
chmod 750 /etc/elasticsearch

chown root.logstash /etc/logstash/conf.d/30-lumberjack-output.conf
chmod 640 /etc/logstash/conf.d/30-lumberjack-output.conf

chown root.kibana /opt/kibana/config/kibana.yml
chmod 640 /opt/kibana/config/kibana.yml
```

Before adding ACL make sure you deny all access to Kibana for users.
Uncomment in **elasticsearch.yml** parameter **searchguard.allow_all_from_loopback: true**.
And execute on elasticsearch host following:

```
service elasticsearch restart

curl -XPUT "http://localhost:9200/searchguard/ac/ac" -d '{
    "acl": [
    {
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
    },
    {
        "__Comment__": "Allow Logstash server user manage logstash indices",
        "users": ["kibana"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-server"]
    },
    {
        "__Comment__": "Allow Kibana server user manage logstash indices",
        "users": ["logstash"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-server"]
    },
    {
        "__Comment__": "Allow administrators group manage Kibana indices",
        "roles": ["kibana-admins"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-admin"]
    },
    {
        "__Comment__": "Allow administrators group read all Logstash indices",
        "roles": ["kibana-admins"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user"]
    },
    {
        "__Comment__": "Allow users group read Kibana indices",
        "roles": ["kibana-users"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-user"]
    },
    {
        "__Comment__": "Allow users group read all Logstash indices",
        "roles": ["kibana-users"],
        "indices": ["logstash-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user"]
    }
    ]
}'

```

Then comment back **searchguard.allow_all_from_loopback: true** and restart all together:

```
service elasticsearch restart && service kibana restart && service logstash restart
```

Now you can open Kibana to users and test authentication.

# How it works
* All IPA users in IPA group **kibana-users** can only read kibana and logstash indices.
* All IPA users in IPA group **kibana-admins** can edit kibana and read logstash indices.
* All grants were taken from official Shield documentation.
* If you need group **kibana-devs** that can only read indices **logstash-nginx-*** then
** in IPA create user **kibana.dev**
** in IPA create group **kibana-devs**
** in IPA add group **kibana-devs** to group **elastic-users**
** in IPA add user **kibana.dev** to group **kibana-devs**
** Apply ACL with added rule:

``` 
    {
        "__Comment__": "Allow devs group read Kibana indices",
        "roles": ["kibana-devs"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-user"]
    },
    {
        "__Comment__": ""Allow devs group read specific Logstash indices",
        "roles": ["kibana-devs"],
        "indices": ["logstash-nginx-*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.logstash-user"]
    }
```

# Problems
* There is a bug that allow authenticated users to see LDAP Bind username and passwords in elasticsearch by executing query:

```
curl -XGET -u user -v -XGET 'http://localhost:9200/_nodes?pretty'
```

This can be overrided by using digest passwords **searchguard.authentication.settingsdb.digest**, but I don't see any much profit of using digest, because while you don't give access to elasticsearch directly (not through Kibana) it's not a problem at all. Fix me if I wrong :-)
* In current state I found that **dlsfilters** and **flsfilters** of search-guard breaks Kibana, so for now you need to use per indice-access (like Shield does)
* To apply ACL elasticsearch must be started with **searchguard.allow_all_from_loopback: true** and set to **false** and restarted after ACL applied.

**Comment by SergeyBear** [comment]
Made some changes to simplify ACL management (moved service users outside of elastic-users group and allowed by default read kibana indices for all elastic-users)

**Comment by ld57** [comment]
Super, thanks for your contrib !

**Comment by SergeyBear** [comment]
Glad to help

**Comment by atom992** [comment]
How about marvel config?
I got error like this:

Server returned HTTP response code: 401 for URL: http://0.0.0.0:9200/_template/marvel
[2015-10-13 05:27:25,992][ERROR][marvel.agent.exporter    ] [Junta] could not connect to any configured elasticsearch instances: [0.0.0.0:9200]
[2015-10-13 05:27:26,003][ERROR][marvel.agent.exporter    ] [Junta] error adding the marvel template to [0.0.0.0:9200] response code [401 Unauthorized]. content: []
[2015-10-13 05:27:26,003][ERROR][marvel.agent.exporter    ] [Junta] failed to verify/upload the marvel template to [0.0.0.0:9200]:
Server returned HTTP response code: 401 for URL: http://0.0.0.0:9200/_template/marvel

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
