### ISSUE TITLE
Elasticsearch Authentication and Authorization Backend

### ISSUE THREAD

**Issue by b0c1** [floragunncom/search-guard#31]
Hi,

You planed to create elasticsearch authentication backend? I mean the authentication information comes from the elasticsearch itself so in settings you define an index (where the user comes from, and of course prereq.. add an admin user before the plugin install) but after that the users can be managed by admin users. (not just authentication but authorization too)

b0c1

**Comment by floragunncom** [comment]
yes, its planned

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
