### ISSUE TITLE
[WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:data/write/bulk[s] (class org.elasticsearch.action.bulk.BulkShardRequest) due to type[s]() method not found

### ISSUE THREAD

**Issue by daniel-ruess** [floragunncom/search-guard#33]
This error message is generating over 60mb worth of logs in a development/testing environment with a fraction of the transactions of production; I need to find a way to get rid of this error since it's logged so many times per second.

You mentioned a possible solution here, https://github.com/floragunncom/search-guard/issues/16#issuecomment-115269045 however I cannot seem to move forward from there.

**Comment by floragunncom** [comment]
Will fix it in the next version, for now you can try this:

In logging.yml:<code><pre>
es.logger.level: INFO
rootLogger: ${es.logger.level}, console, file
logger:
...
com.floragunn.searchguard.filter.SearchGuardActionFilter: ERROR
...
</pre></code>

**Comment by daniel-ruess** [comment]
Appreciate it; I was hoping to continue logging other warnings but this can work until the patch comes in.

Thanks.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
