### ISSUE TITLE
Kibana/Timelion : Kerberos/Spnego authentication failed

### ISSUE THREAD

**Issue by toto23** [floragunncom/search-guard#347]
Versions 
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
elasticsearch-5.3.2
kibana-5.3.2-linux-x86_64
search-guard-5
Red Hat Enterprise Linux Server release 7.3 (Maipo)

On kibana, Kerberos/Spnego authentication works well except for timelion.
** I got a "Timelion: Authentication Exception" on the ui.
** I got this message in the log :
[2017-05-29T17:06:51,938][WARN ][com.floragunn.dlic.auth.http.kerberos.HTTPSpnegoAuthenticator] Service login not successful due to java.security.PrivilegedActionException: GSSException: Failure unspecified at GSS-API level (Mechanism level: Request is a replay (34))

I think it is to related to the issue "Authentication not being passed to kibana plugins #191"
I don't undestand if the issue is resolved or not ? Did i missed something ?

Thanks.

**Comment by floragunncom** [comment]
Agreed, Kibana and SSO like Kerberos and/or JWT is not really well documented, we will add some exampled to the docs soon.

The reason you are seeing this is the way Kibana operates: In most cases when you issue a request to Kibana, it generates exactly one call to Elasticsearch, and then displays the result. However, in other cases, Kibana generates multiple calls to ES under the hood. 

Kerberos/SPNEGO has a security mechanism called "Replay Cache". The replay cache makes sure that an Kerberos/SPENGO token can be used only once in a specific timeframe. 

The Kerberos/SPNEGO tokens are generated by the Browser with the underlying GSSAPI and put in the HTTP header.

Now - if a call to Kibana results in multiple calls to ES, there is only one SPNEGO/Kerberos token that Kibana can use, namely the one in the initial request. Kibana uses this (single) token for all subsequent request to ES, and since the calls are issued in a very short amount of time, they are seen as a replay attack. Kibana does not go back to the browser to get a different ticket for all subrequests, so there is actually no clean way to handle this in our plugin.

The only way to make Kerberos SSO work with Kibana is to disable the replay cache. This is of course not optimal, but so far the only known way.

With Oracle JDK, you can set

# disable replay cache for Kibana to work with Kerberos
-Dsun.security.krb5.rcache=none

in jvm.options of Elasticsearch. With this setting, Kerberos works fine out of the box now, however, the security level is lowered a bit of course.

Will close this issue once the documentation is updated.

**Comment by toto23** [comment]
Understood, thanks for the all explanation. I will test this.

**Comment by floragunncom** [comment]
Docs updated: https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md
