### ISSUE TITLE
Secure Client-Initiated Renegotiation is enabled

### ISSUE THREAD

**Issue by alesnav** [floragunncom/search-guard#362]
Hello there!

After the first pentest performed over the preproduction environment, we have detected one weak configuration, which could be the root cause for a Denial-of-Service (DoS) using the 9200/TCP port.

Please, disable Secure Client-Initiated Renegotiation in all SSL/TLS ports. Now, I don't see any config option to get it done, so I think that this is not implemented.

Thanks!

**Comment by floragunncom** [comment]
**For ES 5.x:**
Pls. have a look into the [SearchGuardSSLPlugin](https://github.com/floragunncom/search-guard-ssl/blob/5.0.0/src/main/java/com/floragunn/searchguard/ssl/SearchGuardSSLPlugin.java#L61) source code. We issue a warning if client initiated renegotiation is not disabled. At least to my knowledge the only way to disable it in Java 8 is setting `jdk.tls.rejectClientInitiatedRenegotiation=true`. But this has to be added manually to the ES_JAVA_OPTS or config/jvm.options. If you use OpenSSL (instead of Java SSL) its the same.

See also https://blog.ivanristic.com/2014/03/ssl-tls-improvements-in-java-8.html and

**Comment by alesnav** [comment]
I tried it, but does not work. Perhaps I did something wrong, but it seems right.

Appended in `/etc/elasticsearch/jvm.conf`:
```
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.tls.disabledAlgorithms=SSLv2Hello,SSLv3,TLSv1,TLSv1.1
```

Command `ps aux | grep elasticsearch` shows that these two args have been loaded into the `/bin/java` initial command.

Connections using TLSv1.1 and TLS1.2 are still supported, and Secure Renegotiation is enabled, too. So, TLSv1.1 and Secure Renegotiation are not disabled.

Am I doing something wrong?

Thanks!

**Comment by floragunncom** [comment]
What is your JVM vendor/version? Pls post output of `java -version` and of your `ps aux | grep elasticsearch` command as well. How did you test if secure client side renego is disabled?

And instead of `jdk.tls.disabledAlgorithms` try `jdk.tls.client.protocols` cause `jdk.tls.disabledAlgorithms` is a **security** property (not a **system** property) and must be defined therefore in $JAVA_HOME/jre/lib/security/java.security

You can also configure this in elasticsearch.yml with
<pre>
# Enabled SSL cipher suites for transport protocol (only Java format is supported)
# WARNING: Expert setting, do only use if you know what you are doing
# If you set wrong values here this this could be a security risk
#searchguard.ssl.transport.enabled_ciphers:
#  - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
#  - "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256"
  
# Enabled SSL protocols for transport protocol (only Java format is supported)
# WARNING: Expert setting, do only use if you know what you are doing
# If you set wrong values here this this could be a security risk  
#searchguard.ssl.transport.enabled_protocols:
#  - "TLSv1.2"

# Enabled SSL cipher suites for http protocol (only Java format is supported)
# WARNING: Expert setting, do only use if you know what you are doing
# If you set wrong values here this this could be a security risk
#searchguard.ssl.http.enabled_ciphers:
#  - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
#  - "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256"

# Enabled SSL protocols for http protocol (only Java format is supported)
# WARNING: Expert setting, do only use if you know what you are doing
# If you set wrong values here this this could be a security risk  
#searchguard.ssl.http.enabled_protocols:
#  - "TLSv1.2"
</pre>

**Comment by alesnav** [comment]
Ok,TLS1.2 is now the only protocol enabled, using this parameters in `elasticsearch.yml`:
```
searchguard.ssl.transport.enabled_protocols: "TLSv1.2"
searchguard.ssl.http.enabled_protocols: "TLSv1.2"
```

This is the output of both commands (CentOS 7.3, ES installed via repo):

```
[root@csmmsevp0009 ~]# java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

[root@csmmsevp0009 ~]# ps aux | grep elasticsearch
elastic+ 31302 53.0 32.8 8228204 2631488 ?     Ssl  08:29   0:23 /bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Djdk.tls.rejectClientInitiatedRenegotiation=true -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-5.3.0.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet -Edefault.path.logs=/datos/elasticsearch/logs -Edefault.path.data=/datos/elasticsearch/data -Edefault.path.conf=/datos/elasticsearch/conf
```

And this is my test:

```
[root@csmmsevp0009 ~]# openssl s_client -connect csmmsevp0009:9200 -tls1_2
CONNECTED(00000003)
[...]
...Certificate information...
[...]
---
SSL handshake has read 4268 bytes and written 453 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 59673044544E6C6F3319D1DFECAFA1AC27E86478F7646265F7EA429A28A00993
    Session-ID-ctx:
    Master-Key: 045AAE79AEC94E79D3475FFF0EA6EB60E7C2DE859273D7E7F1D30F4C9B6FCDCEB2CAD8E2A3BE35C0EE9FF1DDAFD025D0
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1499934788
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
^C
[root@csmmsevp0009 ~]#
```

**Comment by floragunncom** [comment]
With your openssl you check server side renegotiation (and "Secure Renegotiation IS supported" is the expected secure output). To check client side renego you need to do something like

<pre>
openssl s_client -connect host:port
HEAD / HTTP/1.0
R
<Enter or Return key>
</pre>

**Comment by alesnav** [comment]
You're right.

It does work perfect by setting `-Djdk.tls.rejectClientInitiatedRenegotiation=true` in `/etc/elasticsearch/jvm.conf`

Thanks!
