### ISSUE TITLE
Allow change of ACL when searchguard.allow_all_from_loopback: false

### ISSUE THREAD

**Issue by johngilden** [floragunncom/search-guard#37]
Hello,

I'd like to be able to change the ACL from one of my roles (admin) even when `searchguard.allow_all_from_loopback: false` is set. All my users access ES from localhost, so I can't really set this to on, however I don't want to restart ES twice each time I want to change the ACL. Is this somehow possible?

This is what I get from my cURL call `curl -u admin:adminpassword -XPUT 'http://localhost:9200/searchguard/ac/ac' -d` ...:
```
{"error":"RuntimeException[java.lang.RuntimeException: Only allowed from localhost (loopback)]; nested: RuntimeException[Only allowed from localhost (loopback)]; ","status":500}
```

**Comment by floragunncom** [comment]
This is already known, will be fixed in the next version

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
