### ISSUE TITLE
PrivilegesEvaluator will never evaluate true for certain indices actions

### ISSUE THREAD

**Issue by jcantrill** [floragunncom/search-guard#377]
Trying to export UI Kibana objects  leads to a 403 error for permissions.  Looking through the PrivilegesEvaluator code[1], there is no permission to which I can allow this action unless I have admin creds.  We experience this issue in 2.4.4.10 but still see it in master [1].  

The way I read this code:
* Get the cluster actions allowed for the role -> `cluster:*`
* Compare cluster actions against requested action -> `indices:data/read/scroll` vs `cluster:anythinghere`
* Continue to next role because previous step will never match based on [2] from previous step

This looks as if it will always fail any of the following actions [3]

[1] https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/configuration/PrivilegesEvaluator.java#L350
[2] https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/support/WildcardMatcher.java#L111
[3] https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/configuration/PrivilegesEvaluator.java#L350-L360

I am currently testing with:

* Search Guard and Elasticsearch version
ES - 2.4.4 
SG -  2.4.4.10

sample role:

```
    "test_role" : {
     "cluster" : ["*"],
      "indices" : {
        "project?myproject?fd7db3d3-890d-11e7-b9c2-52540050d5ea?*" : {
          "*" : [ "INDEX_PROJECT" ]
        },
        "myproject?fd7db3d3-890d-11e7-b9c2-52540050d5ea?*" : {
          "*" : [ "INDEX_PROJECT" ]
        }
      }
    }
```
I do not know the reason why these specific ones are excluded to offer a possible solution

**Comment by jcantrill** [comment]
I see I can resolve issue by adding 
`indices:data/read/scroll` as a cluster permmision though per [1] I dont think it falls under the list of 'cluster' privileges.

[1] https://www.elastic.co/guide/en/shield/2.1/reference.html#ref-actions-list

**Comment by floragunncom** [comment]
`indices:data/read/scroll` is a cluster permissions because it does, internally api wise, not have a relation to indices. The first search request which initiated the search does have this of course but subsequent scroll requests not. So its not possible to check agains index permissions. What we check instead is that the same user who initiated the first search must be the same which issue the  subsequent scroll requests. So for now you are right, just allow `indices:data/read/scroll` on cluster level.

This also affects higher level request like Reindex or *byQuery request cause they use search and scroll internally.

**Comment by floragunncom** [comment]
see also https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/search-guard/HO8cKiZU3BY/cG_cAzSxBAAJ

**Comment by floragunncom** [comment]
@jcantrill can we close this?
