### ISSUE TITLE
searchguard.ssl.transport.node.encforce_hostname_verification

### ISSUE THREAD

**Issue by macdrai** [floragunncom/search-guard#43]
Hello,

I was wondering if the variable searchguard.ssl.transport.node.en**c**force_hostname_verification is correctly spelled. I'm not sure the c must be there.

**Comment by floragunncom** [comment]
You're right, thx, its a typo. But to make it work you have really to spell it 'wrong'

Will fix this for the above settings:

<pre>
# Enforce hostname verification
#searchguard.ssl.transport.node.encforce_hostname_verification: true
# If hostname verification specify if hostname should be resolved
#searchguard.ssl.transport.node.encforce_hostname_verification.resolve_host_name: true
</pre>

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
