### ISSUE TITLE
Stable Releases for ES 6.0.x Missing

### ISSUE THREAD

**Issue by numbnut** [floragunncom/search-guard#436]
Hi,

I'm missing releases for the ES 6.0.x versions. There is only the beta release available. Is there any reason for not releasing them?

Thank you!

**Comment by jochenkressin** [comment]
The main reason is that almost all of our customers and users wanted to wait until 6.1.x before upgrading their production systems. This is mainly due to bad experiences with the 5.0.x line last year. So we decided to release the GA for 6.1.x onwards only.

So my question is, is there a reason why you can't use 6.1.x and need the GA for 6.0.x? Because if there's a real need, of course, we will think about shipping a GA for 6.0.x as well. Thanks!

**Comment by numbnut** [comment]
Thanks for the quick response. We started upgrading to 6.0.x, but now we might switch to 6.1.x. I need to discuss this. I will come back to you next week. Hopefully things cleared up than.

**Comment by jochenkressin** [comment]
Sure, let us know the outcome and we can plan from there. We usually recommend waiting for / using Elasticsearch 6.1.x  in production and avoid Elasticsearch 6.0.x, but if really required we can provide a GA for 6.0.x.

**Comment by numbnut** [comment]
We decided to go for 6.1.x. No need to release 6.0.x. Thanks for the quick response!
