### ISSUE TITLE
Password dependent timing side channel in AuthCredentials

### ISSUE THREAD

**Issue by madblobfish** [floragunncom/search-guard#439]
In https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/user/AuthCredentials.java#L170 passwords are hashed and then compared using java.util.Arrays.equals.

Arrays.equals seems to provide a timing side channel (tested this [here](https://gist.github.com/madblobfish/426fae0fbccfb9b03aec60e07729819c)), the leakage of password data should be prevented.
The result is that an attacker can find out the credentials faster than with a normal bruteforce attack. It is not impossible to use this attack over the internet, but it is even more dangerous when used over the LAN or from the same machine: http://www.cs.rice.edu/~dwallach/pub/crosby-timing2009.pdf

Note: There are tools which automate the attack, e.g.: https://github.com/aj-code/TimingIntrusionTool5000

**Comment by floragunncom** [comment]
Thanks for reporting this. We will fix this by replacing Arrays.equals() with MessageDigest.isEqual() which is time constant). Since Arrays.equals() here is used only to determine if the user credentials are cached (or not) we do not believe, as of now, that this is a real attack vector which could be exploited in the wild.

**Comment by floragunncom** [comment]
Fixed for SG 5.6.7-19 and 6.1.x-21.0 released today
