### ISSUE TITLE
How to use search-guard with kibana4 implement access control with elasticsearch?

### ISSUE THREAD

**Issue by dc1ps2** [floragunncom/search-guard#44]
Hi , i was install elasticsearch plugin: "search-guard" with running , I would like to implement kibana to elasticsearch immediate access control through search-guard, then i don't how to configuration kibana with search-guard or elasticsearch. 

thank a lot

**Comment by nightsong** [comment]
The index of Kibana4 was named ".kibana".That's will be OK,if you set ACL for this index.

**Comment by dc1ps2** [comment]
first thank for your support, but I mean, i want know kibana4 how to dynamic login  access on the search-guard setted  account ?

**Comment by surewecan** [comment]
It works properly In kibana config, you should specify kibana_elasticsearch_username/kibana_elasticsearch_password from the SG configuration in order to access indexes. As @nightsong  specified, you'll need to add .kibana index to the allowed list for search.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
