### ISSUE TITLE
Current sg_kibana_user defined in master cannot save their work - e.g. new visualisation or edits.

### ISSUE THREAD

**Issue by matuskapetr** [floragunncom/search-guard#465]
Role definition "sg_kibana_user" in current master (commit 983e3a0  on 4 Feb) is tricky because it does now allow users to **save** their work (e.g. new visualisation/edits in visualisation and so on.).
I guess it would be better to have 2 roles - RO and write/update role.

 - CLUSTER_COMPOSITE_OPS_**RO** should be changed to  - CLUSTER_COMPOSITE_OPS
After this users can save their work.

Current master commit 983e3a0  on 4 Feb):

For users which use kibana, access to indices must be granted separately
sg_kibana_user:
  readonly: true
  cluster:
    - MONITOR
    - CLUSTER_COMPOSITE_OPS_**RO**
  indices:
    '?kibana':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '*':
      '*':
        - indices:data/read/field_caps*

**Comment by jochenkressin** [comment]
I don't think I fully understand the issue here. Are you saying that when assigning the sg_kibana_user role to a user, this user is not able to save Visualizations or Dashboards? If this is the case I cannot reproduce this behavior. Do you have a step-by-step instruction on how to reproduce it?

The CLUSTER_COMPOSITE_OPS_RO action group should be sufficient for saving shared objects. Maybe we have missed a special use case?

**Comment by floragunncom** [comment]
@matuskapetr ping

**Comment by floragunncom** [comment]
no feedback, assume solved
