### ISSUE TITLE
What settings need to be enabled if only Kerberos authentication is need for user accessing ES cluster

### ISSUE THREAD

**Issue by ajaybhatnagar** [floragunncom/search-guard#48]
What all settings need to be enabled to use search-guard for Kerberos authentication to access elasticsearch cluster and Kibana users. Configuration settings added:

OS level authentication after kinit is ok on the server and verified with klist.

## Authentication  Kerberos
searchguard.key_path: /var/tmp
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator
searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.AlwaysSucceedAuthenticationBackend

# If caching is enabled then the authentication succeed for 24 h since the first successful login without hitting the backend again and again
#searchguard.authentication.authentication_backend.cache.enable: true

#searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.spnego.HTTPSpnegoAuthenticator
# Absolute file path to krb5 config file
searchguard.authentication.spnego.krb5_config_filepath: /etc/krb5.conf

**Comment by floragunncom** [comment]
pls. see https://github.com/floragunncom/search-guard/blob/master/src/test/java/com/floragunn/searchguard/SfSpNegoTest.java

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
