### ISSUE TITLE
session timeout

### ISSUE THREAD

**Issue by nitram4** [floragunncom/search-guard#49]
when basic authentication used after succesfull login i was not able to logout from kibana4 (not even after day or so) and the session not expire. Any possibility to implement this?

**Comment by floragunncom** [comment]
do you have set <pre>searchguard.http.enable_sessions: true</pre>? If not then its you browser which caches the authentication information.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
