### ISSUE TITLE
SG & Kibana

### ISSUE THREAD

**Issue by julienbeclin** [floragunncom/search-guard#50]
Was anybody able to make SG work with Kibana for file and document filtering per user ? 
Thanks !

**Comment by SergeyBear** [comment]
Hi
Have same problem - when trying to enable dlsfilters in search-guard (elasticsearch 1.5.2 and kibana 4.1.1) Kibana starts to fail even when running and login as admin.

**Comment by etfeet** [comment]
im using 3.1 and kibana bypasses the document filters.

**Comment by jayeshdhamechai** [comment]
Hi,

Anyone able to setup up document level filters on kibana index?
I wish to have access control on kibana dashboards. Could not find much documentation around document level filters.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
