### ISSUE TITLE
pre-generate node key

### ISSUE THREAD

**Issue by bilsch** [floragunncom/search-guard#54]
Is it possible to pre-generate the node key in some way?

https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/service/SearchGuardService.java#L130-L153

It would be handy in cases of doing something like puppet/chef to manage search-guard/elasticsearch setups rather than having to bring up an instance to get a key and then drop that in to puppet for population on the nodes.

Looking at the code I may be able to write up a bit of ruby code to generate the key. Maybe a java class which calls the same bit of java code to avoid duplication if the key format changes?

**Comment by bilsch** [comment]
in case anyone is interested in doing something like this its pretty easy. I got funky problems if I used f.puts as it put a newline char in there causing the key load to complain about the key being 17 bytes instead of 16.

```
    cipher = OpenSSL::Cipher.new('aes-128-cbc')
    cipher.encrypt
    key = cipher.random_key
    File.open("/path/to/foo", 'w') do |f|
      f.write(key)
    end
```

**Comment by ewolinetz** [comment]
Another way to approach this (the way that I took) was the following line:
openssl rand 16 | openssl enc -aes-128-cbc -nosalt -out ./searchguard_node_key.key -pass pass:pass

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
