### ISSUE TITLE
SGAdmin replaces internal users when new configs are applied

### ISSUE THREAD

**Issue by gsaxam** [floragunncom/search-guard#552]
We tried to apply new configurations (roles) using `sg_roles.yml` to our existing cluster and were surprised to learn that all existing internal users were wiped out (including the admin role). We had created users previously using the SG role management APIs and there seems to be no way to persist them or a flag that would indicate if we wanted to preserve existing internal roles.

ES version: 6.1.2

**Comment by jochenkressin** [comment]
Sorry to hear that you expected a different behavior, but that is actually how it is supposed to work.

sgadmin will take the contents of either all configuration files, or a single one (depending on the switches you use), and replace the content in the Search Guard configuration index with the contents of the configuration files. It's always a one-or-nothing operation.

Trying to preserve resources (users, roles, mappings) based on the source of the change would lead to all sorts of strange effects and hard to debug cases. So if you want to use sgadmin in combination with the REST API or the config GUI you should download the currently active configuration first before making changes:

https://docs.search-guard.com/latest/sgadmin#backup-and-restore

To improve the user experience with Search Guard I have the following questions:

1. What is your specific use case, i.e. why do you use the REST API plus sgadmin?
2. Why did you think that sgadmin would not overwrite resources created with the API? Was it something in the docs that was not clear?

I'm asking because we're dealing with SG on a daily basis and therefore it is sometimes hard to spot flaws / misunderstandings.

**Comment by lanerjo** [comment]
Example use case... 
1. making changes to users, roles, rolemappings through either the kibana plugin or searchguard api
2. need to apply configuration changes (ie using the sgadmin tool)

Result: All settings that were applied via the API or kibana plugin are lost.

Recommendations:
1. Add a check in the sgadmin tool  compare settings currently in the searchguard index with settings that are about to be applied. WARN user if roles, rolemappings, internal users are going to be changed.

2. Document in **_bold italics_** the expected behavior 

3. Clean up docs with the intent of making easier navigation, warnings, faqs, more detailed documentation

**Comment by salyh** [comment]
What i do is

Use the -r option with sgadmin.sh to retrieve the current configuration. Then edit them in your text editor and push the single file back with the -f and -t option
