### ISSUE TITLE
Logstash ( transport ) => search-guard

### ISSUE THREAD

**Issue by quejinho1988** [floragunncom/search-guard#56]
I have issue with configuring logstash with transport protocol and ssl, keystore, truststore to the search-guard. Since logstash transport protocol does not support ssl with login , keystore i was trying to workaround it with  logstash-output-elasticsearch-shield. It gave me possibility to use those options. 
Yet i am still not able to manage to make it work with search-guard. 
My config for search-guard is simple i have one user with all privliges. I mange to make it work with kibana , and es +es cluster  so it is not sg config / privlige  issue.  
Need to find workaround for logstash in this case

**Comment by floragunncom** [comment]
Why do you not use the http(s) logstash output (instead of transport protocol).
According to [official sources](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html) the "elasticsearch" output which uses http(s) is the recommended way to do it (and thats works fine with Search Guard).

**Comment by quejinho1988** [comment]
Nowdays it is recommended but when i was testing for SearchGuard  http was recommended.
And there were few more issues there that i had to use http. Topic can be closed because it is old now and i had to skip it and find some other workarounds.

Best regards
Sergiusz
