### ISSUE TITLE
Attempt from null to _all indices for indices:data/read/search

### ISSUE THREAD

**Issue by opsline-ankur** [floragunncom/search-guard#59]
java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/search and User [name=admin, roles=[admin]] for action indices:data/read/search

Hello, I was trying to get this plugin work for authentication. but keep on getting the above error, I have the same acl as mentioned in Readme and same elasticsearch.yml as pointed in one of the links. Can someone please guide here ?

**Comment by triumph281** [comment]
searchguard ，the  ACL  index  cannot be search .  it cause such exception,you can search  like this:
http://localhost:9200/logstash*/_search  ,any way, use index name like "logstash*" and eliminate "searchguard"

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
