### ISSUE TITLE
Forbidden Error !

### ISSUE THREAD

**Issue by gugansankar** [floragunncom/search-guard#69]
I just tried few settings in Search-guard. Here some question I have,

searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*", "indices:admin/get"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:*", "indices:admin/*", "indices:data/write*"]

You can see, 
   **"indices:admin/*"** is enabled in **forbidden section**
   **"indices:admin/get"** is enabled in **allowed_actions.** 

Here, Forbidden section take precedence which is executed first. So I tried to bypass admin/get request like below,

searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*" ]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:*", "indices:admin/*", "indices:data/write*"]
**searchguard.actionrequestfilter.testonly.allowed_actions: ["indices:admin/get"]**
  
ACL config :
  **{
      "__Comment__": "Demo ACL",
      "users": ["demo"],
      "indices": ["demo-*"],
      "filters_bypass": ["actionrequestfilter.testonly"],
      "filters_execute": ["actionrequestfilter.readonly"]
    }**

But, this too comes with 403 forbidden error.

**Comment by balubollam** [comment]
Hi 

I think that error will come according to your default configuration in your index,Please once change your default configuration with different possibilities and try it out

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
