### ISSUE TITLE
 I thinks this  is rubbish, I just need add basic auth, But now I can't init search guard, so many cert need config, I make sure cert is right, but alway wrong, cert have different type, why I can't download,and open basic auth will success, ,it's so complex and not make sence, nginx is wonderful tools, you is rubbish 

### ISSUE THREAD

**Issue by TimLiu1** [floragunncom/search-guard#696]
I thinks this  is rubbish, I just need add basic auth, But now I can't init search guard, so many cert need config, I make sure cert is right, but alway wrong, cert have different type, why I can't download,and open basic auth will success, ,it's so complex and not make sence, nginx is wonderful tools, you is rubbish

**Comment by TimLiu1** [comment]
and the document is not make sence and clear. now I don't know how to init search guard. search rubbish!!!

**Comment by jochenkressin** [comment]
Thank you very much for your constructive post. Here is the clear documentation on how to install Search Guard with all required settings and certificates by executing a single script:

https://docs.search-guard.com/latest/demo-installer

So, download, execute the script, and you will get Basic Authentication. Simple, right?

And here we provide two tools that you can use for generating all required certificates automatically:

https://docs.search-guard.com/latest/online-tls-generator
https://docs.search-guard.com/latest/offline-tls-tool

And here is a clear step by step instruction on how to troubleshoot certificate issues:

https://docs.search-guard.com/latest/troubleshooting-tls

If you do not want to make yourself familiar with TLS certificates, then I suggest you do not touch any of the ES security tools out there, since they all use TLS.

**Comment by TimLiu1** [comment]
three team member waste 3 day in order to understand the doc!!!!!!!!!!!!!!!!!!!!!
