### ISSUE TITLE
how can i POST new ACL to es?

### ISSUE THREAD

**Issue by timesgarden** [floragunncom/search-guard#76]
hi fg,

could you tell me how can i post new ACL to ES which has a ACL configuration already?

![image](https://cloud.githubusercontent.com/assets/3774872/12050197/46787162-af2c-11e5-9cde-8c9f8ff70d00.png

**Comment by dotSlashLu** [comment]
For safety, ACL should only be configured from the es machine itself.

**Comment by timesgarden** [comment]
cannot agree more with you.
however, i tried this, but failed(data.json is ACL policy). do you know why? thanks.
    curl -XPUT http://127.0.0.1:9200/searchguard/ac/ac -d @data.json -uadmin:admin

**Comment by dotSlashLu** [comment]
What's the error message? I'm guessing it's because you used file content as data but `curl` won't URL-encode contents in a file thus ES was not able to parse your json.

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
