### ISSUE TITLE
Getting "searchguard.authentication.AuthException: No user user or wrong password" Exception

### ISSUE THREAD

**Issue by vipulvkp** [floragunncom/search-guard#77]
Hi All,
 
Below are my important configurations in elasticsearch.yml:
searchguard.authentication.authorization.settingsdb.roles.my_user: ["sample role"]

and the filter I am using is as below:
searchguard.actionrequestfilter.names: ["readonly"]
searchguard.actionrequestfilter.readonly.allowed_actions: []
searchguard.actionrequestfilter.readonly.forbidden_actions: ["indices:data/write/*","indices:data/read/*","*monitor*","indices:admin*"]

Below is my curl command to create the index that willl set up the ACL rules:
Please Note: I am using http-basic authentication plugin . So in the below curl command I have given the configured auth user and password:

curl -XPUT -u user:user 'http://localhost:9200/searchguard/ac/ac' -d '{
    "acl": [
     {
           "__Comment__": "For my user  all filters  will be executed). This means restricted access on index sample_index.",
           "users": [
               "my_user"
           ],
           "indices": [
            "sample_index"  
           ],
           "filters_bypass": [],
           "filters_execute": ["*"]
     }
     ]
}'

After running this I get the below error:
"{"error":"AuthException[com.floragunn.searchguard.authentication.AuthException: No user user or wrong password (digest: plain/none)]; nested: AuthException[No user user or wrong password (digest: plain/none)]; ","status":500}"

Please help

**Comment by vroomvroomvroom** [comment]
Make sure all items agree with what you set

curl -XPUT -u user:my_user 'http

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
