### ISSUE TITLE
"More than one user found" error when using ldap.

### ISSUE THREAD

**Issue by michakrause** [floragunncom/search-guard#90]
I guess my java environment does not handle result.next() correctly, because I'm getting this error even if there is really only one result.

I don't know java, so I can't fix it myself.

I tried modifying the exception to: 
throw new AuthException("More than one user found:" + result.get().getDn().toString());

This gave me the following error:
[2016-02-15 10:40:45,306][ERROR][com.floragunn.searchguard.rest.DefaultRestFilter] com.floragunn.searchguard.authentication.AuthException: com.floragunn.searchguard.authentication.AuthExcept
ion: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException

But I have no idea what I'm doing here.
Deleting the entire thing everything seams to work OK.

root@elastic02vq:~ # java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by wangyuehong** [comment]
@michakrause 

I have the same problem today.
the reason is ldap search returned a cursor which contains not just ldap entry but also ldap referral.
You can confirm the search result by using `ldapsearch` like  
`ldapsearch -x -h 10.20.**.** -p 389 -D user1@test.local -w abcd -b 'DC=test,DC=local' "(sAMAccountName=user2)"`

we use Active Directory, if set `searchguard.authentication.ldap.userbase` to roof DN(like `DC=test,DC=local`), that error happens.
we solved that by set `searchguard.authentication.ldap.userbase` to a DN under Roof like `OU=users,DC=test,DC=local`.

hope this helps.

**Comment by floragunncom** [comment]
This is fixed in the upcoming LDAP authentication module (https://github.com/floragunncom/search-guard/wiki). Not yet released but will come this month.

Problem was the lack of Referrals support. Should be fixed with the new module. If not pls. feel free to reopen.
